systemservices/client/urls.py
from django.conf.urls import url
from systemservices.client.views import list, new, detail, remove


urlpatterns = [
    url(r'^$', list, name='list'),
    url(r'^new/$', new, name='new'),
    url(r'^detail/(?P<pk>[\w-]+)/$', detail, name='detail'),
    url(r'^remove/(?P<pk>[\w-]+)/$', remove, name='remove'),
]

systemservices/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from systemservices.core.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^client/', include('systemservices.client.urls', namespace='client')),
    url(r'^services/', include('systemservices.services.urls', namespace='services')),
    url(r'^contract/', include('systemservices.contract.urls', namespace='contract')),
    url(r'^product/', include('systemservices.product.urls', namespace='product')),
    url(r'^admin/', admin.site.urls),
]

systemservices/client/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=200)
    cpf = models.CharField('CPF', max_length=11)
    address = models.CharField(max_length=200)
    neighborhood = models.CharField(max_length=200)
    number = models.CharField(max_length=30)
    cep = models.CharField('CEP', max_length=30)
    city = models.CharField(max_length=250)
    email = models.EmailField('E-mail')
    phone = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Cliente'
        ordering = ('created_at',)

    def __str__(self):
        return self.name

systemservices/client/forms.py
from django.forms import ModelForm, TextInput, EmailInput
from systemservices.client.models import Client


class ClientModelForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['created_at']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'cpf': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'neighborhood': TextInput(attrs={'class': 'form-control'}),
            'number': TextInput(attrs={'class': 'form-control'}),
            'cep': TextInput(attrs={'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'phone': TextInput(attrs={'class': 'form-control'}),
        }

systemservices/client/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from systemservices.client.forms import ClientModelForm
from systemservices.client.models import Client


def list(request):
    clients = Client.objects.all()
    return render(request, 'client/client_list.html', {'clients': clients})


def new(request):
    if request.method == 'POST':
        form = ClientModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully registered client.')
        else:
            messages.error(request, 'Error registered client.')
    return render(request, 'client/client_new.html', {'form': ClientModelForm})


def detail(request, pk):
    form = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientModelForm(request.POST, instance=form)
        if form.is_valid():
            form = form.save()
            messages.success(request, 'Successfully updated client.')
        else:
            messages.error(request, 'Error updated client.')
    form = ClientModelForm(instance=form)
    return render(request, 'client/client_detail.html', {'form': form})


def remove(request, pk):
    Client.objects.get(pk=pk).delete()
    clients = Client.objects.all()
    return render(request, 'client/client_list.html', {'clients': clients})

systemservices/client/templates/client/client_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Update Client</h2>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            {% if messages %}
                {% include 'messages.html' with messages=messages %}
            {% endif %}
            <form method="POST" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-success">
            <input type="reset" value="Clear" class="btn btn-warning">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

systemservices/client/templates/client/client_list.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Customers</h2>
    <a href="{% url 'client:new' %}"><button class="btn btn-default">Create</button></a>
</div>
<div class="row">
    <div class="well bs-component">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>CPF</th>
                    <th>Neighborhood</th>
                    <th>CEP</th>
                    <th>City</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                    <tr>
                        <td><a href="{% url 'client:detail' pk=client.pk %}">{{ client.name }}</a></td>
                        <td>{{ client.cpf }}</td>
                        <td>{{ client.neighborhood }}</td>
                        <td>{{ client.cep }}</td>
                        <td>{{ client.city }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.phone }}</td>
                        <td><a href="{% url 'client:remove' pk=client.pk %}"><button class="btn btn-sm btn-danger">Delete</button></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

systemservices/client/templates/client/client_new.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Registration Client</h2>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            {% if messages %}
                {% include 'messages.html' with messages=messages %}
            {% endif %}
            <form method="POST" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-success">
            <input type="reset" value="Clear" class="btn btn-warning">
            </form>
        </div>
    </div>
</div>
{% endblock content %}