systemservices/product/urls.py
from django.conf.urls import url
from systemservices.product.views import list, new, detail, remove

urlpatterns = [
    url(r'^$', list, name='list'),
    url(r'^new/$', new, name='new'),
    url(r'^detail/(?P<pk>[\w-]+)/$', detail, name='detail'),
    url(r'^remove/(?P<pk>[\w-]+)/$', remove, name='remove'),
]

systemservices/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from systemservices.core.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^client/', include('systemservices.client.urls', namespace='client')),
    url(r'^services/', include('systemservices.services.urls', namespace='services')),
    url(r'^contract/', include('systemservices.contract.urls', namespace='contract')),
    url(r'^product/', include('systemservices.product.urls', namespace='product')),
    url(r'^admin/', admin.site.urls),
]

systemservices/product/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=150)
    model = models.CharField(max_length=150)
    value = models.DecimalField(decimal_places=3, max_digits=20)
    description = models.TextField(max_length=500)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('-created_at',)
        
    def __str__(self):
        return self.name


class Sale(models.Model):
    product = models.ManyToManyField('product.Product')
    client = models.ForeignKey('client.Client', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Sale'
        verbose_name_plural = 'Sale'
        ordering = ('-created_at', )

    def __str__(self):
        return self.product

systemservices/product/forms.py
from django.forms import ModelForm, TextInput, NumberInput, Textarea
from systemservices.product.models import Product


class ProductModelForm(ModelForm):
    class Meta:
        model = Product
        exclude = ['created_at']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'brand': TextInput(attrs={'class': 'form-control'}),
            'model': TextInput(attrs={'class': 'form-control'}),
            'value': NumberInput(attrs={'class': 'form-control', 'step': 0.25}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'quantity': NumberInput(attrs={'class': 'form-control'}),
        }

systemservices/product/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from systemservices.product.models import Product
from systemservices.product.forms import ProductModelForm


def list(request):
    products = Product.objects.all()
    return render(request, 'product/product_list.html', {'products': products})


def new(request):
    if request.method == 'POST':
        form = ProductModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully registered product.')
        else:
            messages.error(request, 'Error registered product.')
    return render(request, 'product/product_new.html', {'form': ProductModelForm})


def detail(request, pk):
    form = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductModelForm(request.POST, instance=form)
        if form.is_valid():
            form = form.save()
            messages.success(request, 'Successfully updated product.')
        else:
            messages.error(request, 'Error updated product.')
    form = ProductModelForm(instance=form)
    return render(request, 'product/product_detail.html', {'form': form})


def remove(request, pk):
    Product.objects.get(pk=pk).delete()
    products = Product.objects.all()
    return render(request, 'product/product_list.html', {'products': products})

systemservices/product/templates/product/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Update Product</h2>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            {% if messages %}
                {% include 'messages.html' with messages=messages %}
            {% endif %}
            <form method="POST" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-success">
            <input type="reset" value="Clear" class="btn btn-warning">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

systemservices/product/templates/product/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Products</h2>
    <a href="{% url 'product:new' %}"><button class="btn btn-default">Create</button></a>
</div>
<div class="row">
    <div class="well bs-component">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Brand</th>
                    <th>Value</th>
                    <th>Quantity</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td><a href="{% url 'product:detail' pk=product.pk %}">{{ product.name }}</a></td>
                        <td>{{ product.brand }}</td>
                        <td>{{ product.value }}</td>
                        <td>{{ product.quantity }}</td>
                        <td><a href="{% url 'product:remove' pk=product.pk %}"><button class="btn btn-sm btn-danger">Delete</button></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

systemservices/product/templates/product/product_new.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h2>Update Product</h2>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            {% if messages %}
                {% include 'messages.html' with messages=messages %}
            {% endif %}
            <form method="POST" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-success">
            <input type="reset" value="Clear" class="btn btn-warning">
            </form>
        </div>
    </div>
</div>
{% endblock content %}